-- MySQL Script generated by MySQL Workbench
-- Thu Aug 26 12:17:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `tipoUsuario` BIT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesor` (
  `idProfesor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `grupos` VARCHAR(45) NULL,
  `alumnos` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idProfesor`),
  INDEX `fk_Profesor_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo/Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo/Grado` (
  `idGrupo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `idAlumno` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Grupo_idGrupo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_Alumno_Grupo1_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  INDEX `fk_Alumno_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`Grupo/Grado` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `idMateria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calificación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calificación` (
  `idCalificación` INT NOT NULL,
  `Alumno_idAlumno` INT NOT NULL,
  `Materia_idMateria` INT NOT NULL,
  `calificación` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`idCalificación`),
  INDEX `fk_Calificación_Alumno1_idx` (`Alumno_idAlumno` ASC) VISIBLE,
  INDEX `fk_Calificación_Materia1_idx` (`Materia_idMateria` ASC) VISIBLE,
  CONSTRAINT `fk_Calificación_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `mydb`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificación_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posts` (
  `idPost` VARCHAR(45) NOT NULL,
  `Grupo/Grado_idGrupo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  INDEX `fk_Posts_Grupo/Grado1_idx` (`Grupo/Grado_idGrupo` ASC) VISIBLE,
  PRIMARY KEY (`idPost`),
  INDEX `fk_Posts_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_Grupo/Grado1`
    FOREIGN KEY (`Grupo/Grado_idGrupo`)
    REFERENCES `mydb`.`Grupo/Grado` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sub_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sub_posts` (
  `idsub_post` INT NOT NULL,
  `Posts_idPost` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsub_post`),
  INDEX `fk_sub_posts_Posts1_idx` (`Posts_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_sub_posts_Posts1`
    FOREIGN KEY (`Posts_idPost`)
    REFERENCES `mydb`.`Posts` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MateriasXProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MateriasXProfesor` (
  `Profesor_idProfesor` INT NOT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  `Materia_idMateria` INT NOT NULL,
  INDEX `fk_ProfesorXGrupo_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  INDEX `fk_MateriasXProfesor_Grupo1_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  INDEX `fk_MateriasXProfesor_Materia1_idx` (`Materia_idMateria` ASC) VISIBLE,
  CONSTRAINT `fk_ProfesorXGrupo_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `mydb`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MateriasXProfesor_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`Grupo/Grado` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MateriasXProfesor_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
