-- MySQL Script generated by MySQL Workbench
-- Wed Aug 25 16:29:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesor` (
  `idProfesor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `grupos` VARCHAR(45) NULL,
  `alumnos` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `idAlumno` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `grupo` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calificación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calificación` (
  `idMateria` INT NOT NULL,
  `idMaestro` VARCHAR(45) NULL,
  `idGrupos` VARCHAR(45) NULL,
  `tipo_evaluacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Board` (
  `idBoard` INT NOT NULL,
  PRIMARY KEY (`idBoard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posts` (
  `materiaid` INT NOT NULL,
  `postid` VARCHAR(45) NULL,
  `usuarioid` VARCHAR(45) NULL,
  `Board_idBoard` INT NOT NULL,
  PRIMARY KEY (`materiaid`),
  INDEX `fk_Comentario_Board1_idx` (`Board_idBoard` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Board1`
    FOREIGN KEY (`Board_idBoard`)
    REFERENCES `mydb`.`Board` (`idBoard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo` (
  `nombre` INT NOT NULL,
  `idGrupo` VARCHAR(45) NULL,
  `Alumno_idAlumno` INT NOT NULL,
  `Profesor_idProfesor` INT NOT NULL,
  `Board_idBoard` INT NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_Grupo_Alumno_idx` (`Alumno_idAlumno` ASC) VISIBLE,
  INDEX `fk_Grupo_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  INDEX `fk_Grupo_Board1_idx` (`Board_idBoard` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_Alumno`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `mydb`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `mydb`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Board1`
    FOREIGN KEY (`Board_idBoard`)
    REFERENCES `mydb`.`Board` (`idBoard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sub_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sub_posts` (
  `idsub_posts` INT NOT NULL,
  `Posts_materiaid` INT NOT NULL,
  PRIMARY KEY (`idsub_posts`),
  INDEX `fk_sub_posts_Posts1_idx` (`Posts_materiaid` ASC) VISIBLE,
  CONSTRAINT `fk_sub_posts_Posts1`
    FOREIGN KEY (`Posts_materiaid`)
    REFERENCES `mydb`.`Posts` (`materiaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MaestroXGrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MaestroXGrupo` (
  `idMaestroXGrupo` INT NOT NULL,
  `Profesor_idProfesor` INT NOT NULL,
  `Grupo_nombre` INT NOT NULL,
  PRIMARY KEY (`idMaestroXGrupo`),
  INDEX `fk_MaestroXGrupo_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  INDEX `fk_MaestroXGrupo_Grupo1_idx` (`Grupo_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_MaestroXGrupo_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `mydb`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MaestroXGrupo_Grupo1`
    FOREIGN KEY (`Grupo_nombre`)
    REFERENCES `mydb`.`Grupo` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
